#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calendar.Resource", IsApplication=true)]

namespace Calendar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Calendar.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Calendar.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonAddTaskLayout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int calenderViewSelectedWeek = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int button1 = 2131099684;
			
			// aapt resource value: 0x7f06001e
			public const int buttonMenuCancel = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int buttonMenuDel = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int buttonNextDay = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int buttonPreviousDay = 2131099649;
			
			// aapt resource value: 0x7f060022
			public const int buttonTitelTask = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int buttonToday = 2131099683;
			
			// aapt resource value: 0x7f060010
			public const int calendarView1 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int edittextOmschrijving = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int edittextPlaats = 2131099671;
			
			// aapt resource value: 0x7f060008
			public const int edittextShowOmschrijving = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int edittextShowPlaats = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int edittextShowTitel = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int edittextTitel = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int include = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int includeTask = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayoutMenuTask = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int listView1 = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int myListView = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int myTextView = 2131099650;
			
			// aapt resource value: 0x7f06001f
			public const int textItem = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int textView1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int textView3 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int textView4 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int textView5 = 2131099674;
			
			// aapt resource value: 0x7f060005
			public const int textViewShow1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textViewShow2 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int textViewShow3 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int textViewShow4 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textViewShow5 = 2131099661;
			
			// aapt resource value: 0x7f060021
			public const int textViewTitel = 2131099681;
			
			// aapt resource value: 0x7f060019
			public const int timePickerBegin = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int timePickerEind = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int timePickerShowBegin = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int timePickerShowEind = 2131099662;
			
			// aapt resource value: 0x7f060020
			public const int titelImageView = 2131099680;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dag = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listShowAllLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Maand = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int taakLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TaskMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TextViewItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Titlelayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Week = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int CalendarViewTheme = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int CustomTitleStyle = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
